### ISSUE TITLE
Question on how to use ga_lock.

### ISSUE THREAD

**Issue by jsboer** [GlobalArrays/ga#212]
I am new to GA.  The manual say any process attempt to lock a mutex which has already been locked will be a fatal error, and the process locking mutex will enter the critical section. 

My question is, how to prevent other processes lock the locked mutex， for there is no API consult the status of lock. And if more than one process try to lock the mutex, the program will stop for the fatal error. So what is the right way to use lock and mutex? I still can not figure out it after seeing the example in manual, is there any example in more detail? 

Thank you!

**Comment by bjpalmer** [comment]
Sorry, this fell through the cracks but if you are still interested in this issue, here goes. The mutexes were created at the start of the GA project and may have seemed like a useful thing at the time, but as far as I know nobody (or almost nobody) has ever used them. At this point, none of the people that created the mutexes are still around so it is hard to see what the original intent was. I think it may have been to implement operations that are currently handled by the accumulate functions but since these functions are already provided, it is not necessary to use mutexes.
