### ISSUE TITLE
Comex OpenIB missing library symbol

### ISSUE THREAD

**Issue by ajmay81** [GlobalArrays/ga#44]
If I build GA with `--with-ofa` and then try to link against it I get:

    lib/libarmci.a(armci.o): In function `PARMCI_NbAccS':
    armci.c:(.text+0x7b4): undefined reference to `comex_nbacc'

It seems the symbol just doesn't get put into the library:

    > nm ga-mvapich2/lib/libarmci.a | grep -i comex_nbacc
                 U comex_nbacc
                 U comex_nbaccs
                 U comex_nbaccv
    00000000000004c0 T comex_nbaccs
    0000000000000270 T comex_nbaccv
    > nm ga-mvapich2/lib/libcomex.a | grep -i comex_nbacc
    00000000000004c0 T comex_nbaccs
    0000000000000270 T comex_nbaccv

Everything works fine if I instead use `--with-openib`, I just wanted to compare if there was any difference in performance between the two, is the `--with-openib` still the recommended option?

**Comment by MuathNairat** [comment]
I face the same problem here.. everything is fine --with-openib but --with-ofa I get this:

~/nwchem-6.6_comex/src/tools/install/lib/libarmci.a(armci.o): In function `PARMCI_NbAccS':
~/nwchem-6.6_comex/src/tools/build/comex/../../ga-5-6/comex/src-armci/armci.c:355: undefined reference to `comex_nbacc'
make: *** [all] Error 1

**Comment by jeffdaily** [comment]
@ajmay81 For infiniband systems, yes, we still recommend --with-openib.  --with-ofa was a new infiniband implementation using our comex runtime but is not as optimized as --with-openib.  If you are on an infiniband-based system and --with-openib is giving you problems then we recommend --with-pr, our fastest MPI implementation.

Note that this issue is fixed in the hotfix/5.6.1 branch and will close this issue once we release.

**Comment by MuathNairat** [comment]
Thanks a lot Jeff, I will try it, but you mean --with-mpi-pr, right? I cant seem to find --with-pr as an option

**Comment by jeffdaily** [comment]
Yes, I meant --with-mpi-pr.  Sorry for any confusion.
