### ISSUE TITLE
Failed tests with Intel compilers

### ISSUE THREAD

**Issue by Jellby** [GlobalArrays/ga#86]
I guess Intel compilers are not supported, but I'll report it just in case. I've tried with a few 15-17 versions, and there's always at least one failure, often more. For instance, with version 16.0.2 I get crashes in global/testing/g2test.x global/testing/ghosts.x global/testing/mmatrix.x global/testing/sprsmatmult.x global/testing/testmatmult.x global/testing/testspd.x

What I do, after checking out v5.6.1:

```
./autogen.sh
MKL_LINK_LINE="-L$MKLROOT/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64"
./configure MPICC=mpiicc MPIF77=mpiifort FFLAGS=-qopenmp CFLAGS=-qopenmp --enable-i8 --with-openib --with-blas8="$MKL_LINK_LINE" --prefix=$PWD/build
make
make check
```

Of course the problem could be something other than the compiler (MKL, "i8", openib...)

**Comment by jeffhammond** [comment]
I've been building NWChem with Intel Fortran constantly since 2006 and am not aware of any GA issues specific to the Intel compiler.  I suspect the issues you see are in the tests themselves, not the GA library, and I am hesitant to calling them compiler issues unless they compile and run with Fortran compilers besides GCC (i.e. `gfortran`) with standard-compliance enforcing flags.

The best way to drill down the source of the error is to use Netlib BLAS/LAPACK/ScaLAPACK and `ARMCI_NETWORK=MPI-TS`.

**Comment by jeffhammond** [comment]
Please reopen this is it is still an issue.
